package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Edad")
	private java.lang.Integer edad;

	@org.kie.api.definition.type.Label("Perfil")
	private java.lang.Integer perfil;

	@org.kie.api.definition.type.Label("Score")
	private java.lang.Integer score;

	@org.kie.api.definition.type.Label("MontoFinanciado")
	private java.lang.Double montoFinanciado;

	@org.kie.api.definition.type.Label("TotalPatrimonio")
	private java.lang.Double totalPatrimonio;

	@org.kie.api.definition.type.Label("NumeroDeudas")
	private java.lang.Integer numeroDeudas;

	@org.kie.api.definition.type.Label("ValorEntrada")
	private java.lang.Double valorEntrada;

	@org.kie.api.definition.type.Label("ValorFacturable")
	private java.lang.Double valorFacturable;

	@org.kie.api.definition.type.Label("ActividadEconomica")
	private java.lang.String actividadEconomica;

	@org.kie.api.definition.type.Label("TotalIngresos")
	private java.lang.Double totalIngresos;

	@org.kie.api.definition.type.Label("LiquidezBruta")
	private java.lang.Double liquidezBruta;

	@org.kie.api.definition.type.Label("LiquidezNeta")
	private java.lang.Double liquidezNeta;

	@org.kie.api.definition.type.Label("CarteraCastigada")
	private java.lang.Double carteraCastigada;

	@org.kie.api.definition.type.Label("DemandaJudicial")
	private java.lang.Double demandaJudicial;

	@org.kie.api.definition.type.Label("CVencida60D")
	private java.lang.Double CVencida60D;

	@org.kie.api.definition.type.Label("CVencida90D")
	private java.lang.Double CVencida90D;

	@org.kie.api.definition.type.Label("Cuota")
	private java.lang.Double cuota;

	@org.kie.api.definition.type.Label("IngresosNetos")
	private java.lang.Double ingresosNetos;

	@org.kie.api.definition.type.Label("Requisitos")
	private java.lang.String requisitos;

	@org.kie.api.definition.type.Label(value = "Months")
	private java.lang.Integer months;

	public Cliente() {

	}

	public java.lang.Integer getEdad() {
		return this.edad;
	}

	public void setEdad(java.lang.Integer edad) {
		this.edad = edad;
	}

	public java.lang.Integer getPerfil() {
		return this.perfil;
	}

	public void setPerfil(java.lang.Integer perfil) {
		this.perfil = perfil;
	}

	public java.lang.Integer getScore() {
		return this.score;
	}

	public void setScore(java.lang.Integer score) {
		this.score = score;
	}

	public java.lang.Double getMontoFinanciado() {
		return this.montoFinanciado;
	}

	public void setMontoFinanciado(java.lang.Double montoFinanciado) {
		this.montoFinanciado = montoFinanciado;
	}

	public java.lang.Double getTotalPatrimonio() {
		return this.totalPatrimonio;
	}

	public void setTotalPatrimonio(java.lang.Double totalPatrimonio) {
		this.totalPatrimonio = totalPatrimonio;
	}

	public java.lang.Integer getNumeroDeudas() {
		return this.numeroDeudas;
	}

	public void setNumeroDeudas(java.lang.Integer numeroDeudas) {
		this.numeroDeudas = numeroDeudas;
	}

	public java.lang.Double getValorEntrada() {
		return this.valorEntrada;
	}

	public void setValorEntrada(java.lang.Double valorEntrada) {
		this.valorEntrada = valorEntrada;
	}

	public java.lang.Double getValorFacturable() {
		return this.valorFacturable;
	}

	public void setValorFacturable(java.lang.Double valorFacturable) {
		this.valorFacturable = valorFacturable;
	}

	public java.lang.String getActividadEconomica() {
		return this.actividadEconomica;
	}

	public void setActividadEconomica(java.lang.String actividadEconomica) {
		this.actividadEconomica = actividadEconomica;
	}

	public java.lang.Double getTotalIngresos() {
		return this.totalIngresos;
	}

	public void setTotalIngresos(java.lang.Double totalIngresos) {
		this.totalIngresos = totalIngresos;
	}

	public java.lang.Double getLiquidezBruta() {
		return this.liquidezBruta;
	}

	public void setLiquidezBruta(java.lang.Double liquidezBruta) {
		this.liquidezBruta = liquidezBruta;
	}

	public java.lang.Double getLiquidezNeta() {
		return this.liquidezNeta;
	}

	public void setLiquidezNeta(java.lang.Double liquidezNeta) {
		this.liquidezNeta = liquidezNeta;
	}

	public java.lang.Double getCarteraCastigada() {
		return this.carteraCastigada;
	}

	public void setCarteraCastigada(java.lang.Double carteraCastigada) {
		this.carteraCastigada = carteraCastigada;
	}

	public java.lang.Double getDemandaJudicial() {
		return this.demandaJudicial;
	}

	public void setDemandaJudicial(java.lang.Double demandaJudicial) {
		this.demandaJudicial = demandaJudicial;
	}

	public java.lang.Double getCVencida60D() {
		return this.CVencida60D;
	}

	public void setCVencida60D(java.lang.Double CVencida60D) {
		this.CVencida60D = CVencida60D;
	}

	public java.lang.Double getCVencida90D() {
		return this.CVencida90D;
	}

	public void setCVencida90D(java.lang.Double CVencida90D) {
		this.CVencida90D = CVencida90D;
	}

	public java.lang.Double getCuota() {
		return this.cuota;
	}

	public void setCuota(java.lang.Double cuota) {
		this.cuota = cuota;
	}

	public java.lang.Double getIngresosNetos() {
		return this.ingresosNetos;
	}

	public void setIngresosNetos(java.lang.Double ingresosNetos) {
		this.ingresosNetos = ingresosNetos;
	}

	public java.lang.String getRequisitos() {
		return this.requisitos;
	}

	public void setRequisitos(java.lang.String requisitos) {
		this.requisitos = requisitos;
	}

	public java.lang.Integer getMonths() {
		return this.months;
	}

	public void setMonths(java.lang.Integer months) {
		this.months = months;
	}

	public Cliente(java.lang.Integer edad, java.lang.Integer perfil,
			java.lang.Integer score, java.lang.Double montoFinanciado,
			java.lang.Double totalPatrimonio, java.lang.Integer numeroDeudas,
			java.lang.Double valorEntrada, java.lang.Double valorFacturable,
			java.lang.String actividadEconomica,
			java.lang.Double totalIngresos, java.lang.Double liquidezBruta,
			java.lang.Double liquidezNeta, java.lang.Double carteraCastigada,
			java.lang.Double demandaJudicial, java.lang.Double CVencida60D,
			java.lang.Double CVencida90D, java.lang.Double cuota,
			java.lang.Double ingresosNetos, java.lang.String requisitos,
			java.lang.Integer months) {
		this.edad = edad;
		this.perfil = perfil;
		this.score = score;
		this.montoFinanciado = montoFinanciado;
		this.totalPatrimonio = totalPatrimonio;
		this.numeroDeudas = numeroDeudas;
		this.valorEntrada = valorEntrada;
		this.valorFacturable = valorFacturable;
		this.actividadEconomica = actividadEconomica;
		this.totalIngresos = totalIngresos;
		this.liquidezBruta = liquidezBruta;
		this.liquidezNeta = liquidezNeta;
		this.carteraCastigada = carteraCastigada;
		this.demandaJudicial = demandaJudicial;
		this.CVencida60D = CVencida60D;
		this.CVencida90D = CVencida90D;
		this.cuota = cuota;
		this.ingresosNetos = ingresosNetos;
		this.requisitos = requisitos;
		this.months = months;
	}

}