package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DatosOperacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ValorFacturable")
	private java.lang.Double valorFacturable;

	@org.kie.api.definition.type.Label("ValorEntrada")
	private java.lang.Double valorEntrada;

	@org.kie.api.definition.type.Label("MontoFinanciado")
	private java.lang.Double montoFinanciado;

	@org.kie.api.definition.type.Label("ValorCuota")
	private java.lang.Double valorCuota;

	public DatosOperacion() {
	}
	
	public java.lang.Double getValorFacturable() {
		return this.valorFacturable;
	}

	public void setValorFacturable(java.lang.Double valorFacturable) {
		this.valorFacturable = valorFacturable;
	}

	public java.lang.Double getValorEntrada() {
		return this.valorEntrada;
	}

	public void setValorEntrada(java.lang.Double valorEntrada) {
		this.valorEntrada = valorEntrada;
	}

	public java.lang.Double getMontoFinanciado() {
		return this.montoFinanciado;
	}

	public void setMontoFinanciado(java.lang.Double montoFinanciado) {
		this.montoFinanciado = montoFinanciado;
	}

	public java.lang.Double getValorCuota() {
		return this.valorCuota;
	}

	public void setValorCuota(java.lang.Double valorCuota) {
		this.valorCuota = valorCuota;
	}

	public DatosOperacion(java.lang.Double valorFacturable,
			java.lang.Double valorEntrada, java.lang.Double montoFinanciado,
			java.lang.Double valorCuota) {
		this.valorFacturable = valorFacturable;
		this.valorEntrada = valorEntrada;
		this.montoFinanciado = montoFinanciado;
		this.valorCuota = valorCuota;
	}

}