package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DatosCliente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("IdentificacionCliente")
	private java.lang.String identificacionCliente;

	@org.kie.api.definition.type.Label("FechaNacimiento")
	private java.lang.String fechaNacimiento;

	@org.kie.api.definition.type.Label("ActividadEconomica")
	private java.lang.String actividadEconomica;

	@org.kie.api.definition.type.Label("TotalPatrimonio")
	private java.lang.Double totalPatrimonio;

	@org.kie.api.definition.type.Label("TotalIngresos")
	private java.lang.Double totalIngresos;

	@org.kie.api.definition.type.Label("IngresosNetos")
	private java.lang.Double ingresosNetos;

	@org.kie.api.definition.type.Label("LiquidezBruta")
	private java.lang.Double liquidezBruta;

	@org.kie.api.definition.type.Label("LiquidezNeta")
	private java.lang.Double liquidezNeta;

	public DatosCliente() {
	}

	public java.lang.String getIdentificacionCliente() {
		return this.identificacionCliente;
	}

	public void setIdentificacionCliente(java.lang.String identificacionCliente) {
		this.identificacionCliente = identificacionCliente;
	}

	public java.lang.String getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(java.lang.String fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public java.lang.String getActividadEconomica() {
		return this.actividadEconomica;
	}

	public void setActividadEconomica(java.lang.String actividadEconomica) {
		this.actividadEconomica = actividadEconomica;
	}

	public java.lang.Double getTotalPatrimonio() {
		return this.totalPatrimonio;
	}

	public void setTotalPatrimonio(java.lang.Double totalPatrimonio) {
		this.totalPatrimonio = totalPatrimonio;
	}

	public java.lang.Double getTotalIngresos() {
		return this.totalIngresos;
	}

	public void setTotalIngresos(java.lang.Double totalIngresos) {
		this.totalIngresos = totalIngresos;
	}

	public java.lang.Double getIngresosNetos() {
		return this.ingresosNetos;
	}

	public void setIngresosNetos(java.lang.Double ingresosNetos) {
		this.ingresosNetos = ingresosNetos;
	}

	public java.lang.Double getLiquidezBruta() {
		return this.liquidezBruta;
	}

	public void setLiquidezBruta(java.lang.Double liquidezBruta) {
		this.liquidezBruta = liquidezBruta;
	}

	public java.lang.Double getLiquidezNeta() {
		return this.liquidezNeta;
	}

	public void setLiquidezNeta(java.lang.Double liquidezNeta) {
		this.liquidezNeta = liquidezNeta;
	}

	public DatosCliente(java.lang.String identificacionCliente,
			java.lang.String fechaNacimiento,
			java.lang.String actividadEconomica,
			java.lang.Double totalPatrimonio, java.lang.Double totalIngresos,
			java.lang.Double ingresosNetos, java.lang.Double liquidezBruta,
			java.lang.Double liquidezNeta) {
		this.identificacionCliente = identificacionCliente;
		this.fechaNacimiento = fechaNacimiento;
		this.actividadEconomica = actividadEconomica;
		this.totalPatrimonio = totalPatrimonio;
		this.totalIngresos = totalIngresos;
		this.ingresosNetos = ingresosNetos;
		this.liquidezBruta = liquidezBruta;
		this.liquidezNeta = liquidezNeta;
	}

}