package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DatosOperacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("QuskiAutomotriz")
	private java.lang.Double quskiAutomotriz;

	@org.kie.api.definition.type.Label("ValorEntrada")
	private java.lang.Double valorEntrada;

	@org.kie.api.definition.type.Label("MontoFinanciado")
	private java.lang.Double montoFinanciado;

	@org.kie.api.definition.type.Label("ValorCuota")
	private java.lang.Double valorCuota;

	public DatosOperacion() {
	}
	
	public java.lang.Double getQuskiAutomotriz() {
		return this.quskiAutomotriz;
	}

	public void setQuskiAutomotriz(java.lang.Double quskiAutomotriz) {
		this.quskiAutomotriz = quskiAutomotriz;
	}

	public java.lang.Double getValorEntrada() {
		return this.valorEntrada;
	}

	public void setValorEntrada(java.lang.Double valorEntrada) {
		this.valorEntrada = valorEntrada;
	}

	public java.lang.Double getMontoFinanciado() {
		return this.montoFinanciado;
	}

	public void setMontoFinanciado(java.lang.Double montoFinanciado) {
		this.montoFinanciado = montoFinanciado;
	}

	public java.lang.Double getValorCuota() {
		return this.valorCuota;
	}

	public void setValorCuota(java.lang.Double valorCuota) {
		this.valorCuota = valorCuota;
	}

	public DatosOperacion(java.lang.Double quskiAutomotriz,
			java.lang.Double valorEntrada, java.lang.Double montoFinanciado,
			java.lang.Double valorCuota) {
		this.quskiAutomotriz = quskiAutomotriz;
		this.valorEntrada = valorEntrada;
		this.montoFinanciado = montoFinanciado;
		this.valorCuota = valorCuota;
	}

}