package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Informacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("CodigoError")
	private java.lang.String codigoError;
	@org.kie.api.definition.type.Label("Mensaje")
	private java.lang.String mensaje;
	@org.kie.api.definition.type.Label("Identificacion")
	private java.lang.String identificacion;
	public Informacion() {
	}

	public java.lang.String getCodigoError() {
		return this.codigoError;
	}

	public void setCodigoError(java.lang.String codigoError) {
		this.codigoError = codigoError;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public java.lang.String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(java.lang.String identificacion) {
		this.identificacion = identificacion;
	}

	public Informacion(java.lang.String codigoError, java.lang.String mensaje,
			java.lang.String identificacion) {
		this.codigoError = codigoError;
		this.mensaje = mensaje;
		this.identificacion = identificacion;
	}

}