package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Informacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("CodigoError")
	private java.lang.String codigoError;
	@org.kie.api.definition.type.Label("Mensaje")
	private java.lang.String mensaje;
	@org.kie.api.definition.type.Label("Identificacion")
	private java.lang.String identificacion;
	@org.kie.api.definition.type.Label("Resultados")
	private com.relative.QuskiAutomotriz.ObjetosNegocio.Resultados resultados;

	@org.kie.api.definition.type.Label(value = "Politicas")
	private com.relative.QuskiAutomotriz.ObjetosNegocio.Politicas politicas;

	public Informacion() {
	}

	public java.lang.String getCodigoError() {
		return this.codigoError;
	}

	public void setCodigoError(java.lang.String codigoError) {
		this.codigoError = codigoError;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public java.lang.String getIdentificacion() {
		return this.identificacion;
	}

	public void setIdentificacion(java.lang.String identificacion) {
		this.identificacion = identificacion;
	}

	public com.relative.QuskiAutomotriz.ObjetosNegocio.Resultados getResultados() {
		return this.resultados;
	}

	public void setResultados(
			com.relative.QuskiAutomotriz.ObjetosNegocio.Resultados resultados) {
		this.resultados = resultados;
	}

	public com.relative.QuskiAutomotriz.ObjetosNegocio.Politicas getPoliticas() {
		return this.politicas;
	}

	public void setPoliticas(
			com.relative.QuskiAutomotriz.ObjetosNegocio.Politicas politicas) {
		this.politicas = politicas;
	}

	public Informacion(java.lang.String codigoError, java.lang.String mensaje,
			java.lang.String identificacion,
			com.relative.QuskiAutomotriz.ObjetosNegocio.Resultados resultados,
			com.relative.QuskiAutomotriz.ObjetosNegocio.Politicas politicas) {
		this.codigoError = codigoError;
		this.mensaje = mensaje;
		this.identificacion = identificacion;
		this.resultados = resultados;
		this.politicas = politicas;
	}

}