package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Politicas implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ResultadoPoliticas")
	private java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.ResultadoPoliticas> ResultadoPoliticas;

	public Politicas() {
	}

	public java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.ResultadoPoliticas> getResultadoPoliticas() {
		return this.ResultadoPoliticas;
	}

	public void setResultadoPoliticas(
			java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.ResultadoPoliticas> resultadoPoliticas) {
		this.ResultadoPoliticas = resultadoPoliticas;
	}

	public Politicas(
			java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.ResultadoPoliticas> resultadoPoliticas) {
		this.ResultadoPoliticas = resultadoPoliticas;
	}

}