package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Resultados implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Resultado")
	private java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.Resultado> Resultado;

	public Resultados() {
	}

	public java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.Resultado> getResultado() {
		return this.Resultado;
	}

	public void setResultado(
			java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.Resultado> resultado) {
		this.Resultado = resultado;
	}

	public Resultados(
			java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.Resultado> resultado) {
		this.Resultado = resultado;
	}

}