package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResultadoPoliticas implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("Valor")
	private java.lang.Integer valor;
	@org.kie.api.definition.type.Label("Estado")
	private java.lang.String estado;

	public ResultadoPoliticas() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Integer getValor() {
		return this.valor;
	}

	public void setValor(java.lang.Integer valor) {
		this.valor = valor;
	}

	public java.lang.String getEstado() {
		return this.estado;
	}

	public void setEstado(java.lang.String estado) {
		this.estado = estado;
	}

	public ResultadoPoliticas(java.lang.Integer valor, java.lang.String id,
			java.lang.String estado) {
		this.id = id;
		this.valor = valor;
		this.estado = estado;
	}

}