package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VariablesInternas implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "ScoreDeudor")
	private java.lang.Integer scoreDeudor;
	@org.kie.api.definition.type.Label(value = "NumeroDeudas")
	private java.lang.Integer numeroDeudas;
	@org.kie.api.definition.type.Label(value = "TotalDeudas")
	private java.lang.Double totalDeudas;
	@org.kie.api.definition.type.Label(value = "CarteraCastigada")
	private java.lang.Double carteraCastigada;
	@org.kie.api.definition.type.Label(value = "DemandaJudicial")
	private java.lang.Double demandaJudicial;
	@org.kie.api.definition.type.Label(value = "CVencida60D")
	private java.lang.Double CVencida60D;
	@org.kie.api.definition.type.Label(value = "CVencida90D")
	private java.lang.Double CVencida90D;

	public VariablesInternas() {
	}

	public java.lang.Integer getScoreDeudor() {
		return this.scoreDeudor;
	}

	public void setScoreDeudor(java.lang.Integer scoreDeudor) {
		this.scoreDeudor = scoreDeudor;
	}

	public java.lang.Integer getNumeroDeudas() {
		return this.numeroDeudas;
	}

	public void setNumeroDeudas(java.lang.Integer numeroDeudas) {
		this.numeroDeudas = numeroDeudas;
	}

	public java.lang.Double getTotalDeudas() {
		return this.totalDeudas;
	}

	public void setTotalDeudas(java.lang.Double totalDeudas) {
		this.totalDeudas = totalDeudas;
	}

	public java.lang.Double getCarteraCastigada() {
		return this.carteraCastigada;
	}

	public void setCarteraCastigada(java.lang.Double carteraCastigada) {
		this.carteraCastigada = carteraCastigada;
	}

	public java.lang.Double getDemandaJudicial() {
		return this.demandaJudicial;
	}

	public void setDemandaJudicial(java.lang.Double demandaJudicial) {
		this.demandaJudicial = demandaJudicial;
	}

	public java.lang.Double getcVencida60D() {
		return this.CVencida60D;
	}

	public void setcVencida60D(java.lang.Double CVencida60D) {
		this.CVencida60D = CVencida60D;
	}

	public java.lang.Double getcVencida90D() {
		return this.CVencida90D;
	}

	public void setcVencida90D(java.lang.Double CVencida90D) {
		this.CVencida90D = CVencida90D;
	}

	public VariablesInternas(java.lang.Integer scoreDeudor,
			java.lang.Integer numeroDeudas, java.lang.Double totalDeudas,
			java.lang.Double carteraCastigada,
			java.lang.Double demandaJudicial, java.lang.Double CVencida60D,
			java.lang.Double CVencida90D) {
		this.scoreDeudor = scoreDeudor;
		this.numeroDeudas = numeroDeudas;
		this.totalDeudas = totalDeudas;
		this.carteraCastigada = carteraCastigada;
		this.demandaJudicial = demandaJudicial;
		this.CVencida60D = CVencida60D;
		this.CVencida90D = CVencida90D;
	}

}