package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class VariablesNegocio implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Detener")
	private java.lang.Boolean detener;
	@org.kie.api.definition.type.Label("CodigosPoliticas")
	private java.util.List<java.lang.String> codigosPoliticas;

	@org.kie.api.definition.type.Label("Resultado")
	private java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.Resultado> resultado;

	@org.kie.api.definition.type.Label("ResultadoPoliticas")
	private java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.ResultadoPoliticas> resultadoPoliticas;

	@org.kie.api.definition.type.Label(value = "CodigoError")
	private java.lang.String codigoError;

	@org.kie.api.definition.type.Label(value = "Mensaje")
	private java.lang.String mensaje;

	public VariablesNegocio() {

	}

	public java.lang.Boolean getDetener() {
		return this.detener;
	}

	public void setDetener(java.lang.Boolean detener) {
		this.detener = detener;
	}

	public java.util.List<java.lang.String> getCodigosPoliticas() {
		return this.codigosPoliticas;
	}

	public void setCodigosPoliticas(
			java.util.List<java.lang.String> codigosPoliticas) {
		this.codigosPoliticas = codigosPoliticas;
	}

	public java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.Resultado> getResultado() {
		return this.resultado;
	}

	public void setResultado(
			java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.Resultado> resultado) {
		this.resultado = resultado;
	}

	public java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.ResultadoPoliticas> getResultadoPoliticas() {
		return this.resultadoPoliticas;
	}

	public void setResultadoPoliticas(
			java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.ResultadoPoliticas> resultadoPoliticas) {
		this.resultadoPoliticas = resultadoPoliticas;
	}

	public java.lang.String getCodigoError() {
		return this.codigoError;
	}

	public void setCodigoError(java.lang.String codigoError) {
		this.codigoError = codigoError;
	}

	public java.lang.String getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(java.lang.String mensaje) {
		this.mensaje = mensaje;
	}

	public VariablesNegocio(
			java.lang.Boolean detener,
			java.util.List<java.lang.String> codigosPoliticas,
			java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.Resultado> resultado,
			java.util.List<com.relative.QuskiAutomotriz.ObjetosNegocio.ResultadoPoliticas> resultadoPoliticas,
			java.lang.String codigoError, java.lang.String mensaje) {
		this.detener = detener;
		this.codigosPoliticas = codigosPoliticas;
		this.resultado = resultado;
		this.resultadoPoliticas = resultadoPoliticas;
		this.codigoError = codigoError;
		this.mensaje = mensaje;
	}

}