package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlDatosOperacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("DatosOperacion")
	private com.relative.QuskiAutomotriz.ObjetosNegocio.DatosOperacion datosOperacion;

	public XmlDatosOperacion() {
	}

	public com.relative.QuskiAutomotriz.ObjetosNegocio.DatosOperacion getDatosOperacion() {
		return this.datosOperacion;
	}

	public void setDatosOperacion(
			com.relative.QuskiAutomotriz.ObjetosNegocio.DatosOperacion datosOperacion) {
		this.datosOperacion = datosOperacion;
	}

	public XmlDatosOperacion(
			com.relative.QuskiAutomotriz.ObjetosNegocio.DatosOperacion datosOperacion) {
		this.datosOperacion = datosOperacion;
	}

}