package com.relative.QuskiAutomotriz.ObjetosNegocio;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Description("Este objeto guarda el conjunto de objetos DatosCliente del xml de entrada")
public class XmlDatosCliente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("DatosCliente")
	private com.relative.QuskiAutomotriz.ObjetosNegocio.DatosCliente datosCliente;

	public XmlDatosCliente() {
	}

	public com.relative.QuskiAutomotriz.ObjetosNegocio.DatosCliente getDatosCliente() {
		return this.datosCliente;
	}

	public void setDatosCliente(
			com.relative.QuskiAutomotriz.ObjetosNegocio.DatosCliente datosCliente) {
		this.datosCliente = datosCliente;
	}

	public XmlDatosCliente(
			com.relative.QuskiAutomotriz.ObjetosNegocio.DatosCliente datosCliente) {
		this.datosCliente = datosCliente;
	}

}